[package]
name = "toolbox"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
colored = "2.0"
crossterm = "0.22"

[profile.release]
lto = "thin"

